gherkin-lint/gherkin-lint

.gherkin-lintrc
README.md
src/rules/no-partially-commented-tag-lines.js
test-data/PartiallyCommentedTagLine.feature

The gherkin parser doesn't parse partially commented lines in the way you would expect, eg it will break down `@t1 #@t2` in `@t1 #` and `@t2`

adding rule that detect tag line being partially commented out

---

.gherkin-lintrc
README.md
src/formatters/stylish.js
src/linter.js
src/rules.js
src/rules/new-line-at-eof.js
test-data/DuplicateFeatureName-Pt1.feature
test-data/DuplicateFeatureName-Pt2.feature
test-data/NoLineAtEOF.feature
test-data/NoNewLineAtEOF.feature
test-data/PartiallyCommentedTagLine.feature
test-data/TagOnBackground.feature
test-data/UnnamedFeature.feature
test-data/WrongIndentation.feature

1.Adding rule for enforcing/disallowing new line at the EOF
2.Fixing padding for output printing for line numbers that have different number of digits
3.Fixing rule configuration verification, verification would not catch rules that were configured with just one string that wasn't 'on' or 'off' 
4. Fixing typos in several test .feature files

Adding rule for enforcing/disallowing new line at the EOF and bugfixes

---

src/rules/indetation.js

fix: make sure the errors object is empty when a new feature file is parsed

---

src/formatters/json.js
src/formatters/stylish.js

this fixes e.g. output in a Jenkins console, since normal console.log statements are mapped to INFO instead of ERROR

fix: use console.error instead of console.log

---

src/rules/no-trailing-spaces.js
test-data/TrailingTab.feature

If the line ends with one ore more whitespace characters, mark it as an error.
I've added an example with tabs, too

fix: update trailing spaces rule to catch any whitespace character

---

package.json
src/rules/name-length.js
test-data-wip/.gherkin-lintrc
test/rules/name-length/test-data/CorrectLength.feature
test/rules/name-length/test-data/WrongLength.feature
test/rules/name-length/test-results/results.js
test/rules/name-length/test.js

Resolves #51 
This rule raises errors if Feature, Scenario, or Step names are too long.

Add name-length rule

---

src/rules.js

Hi,
I saw that `getRule` method in `rule.js` gets a rule traversing the array of rules. I think that has better performance using a hash of rules.
Regards!

Use a hash to store and get rules.

---

src/rules/use-and.js
test-data-wip/.gherkin-lintrc
test-data-wip/UseAnd.feature

To check that repeated steps like: When, When, Then, Then, Then
Are written using And like: When, And, Then, And, And
When editing feature files, it's easy to make the mistake
of not using And when you should (e.g. when copy-pasting
existing steps to create new ones).  This linting rule ensures
that And is used consistently.
Future improvements:
I guess one might want to either apply this rule, or the opposite
of it - never using And, but repeating the step keywords instead.
For this the rule should be configurable, something like:
use-and: ["on", "always"/"never"]

Implement use-and rule

---

src/main.js

Previously running `gherkin-lint -h` printed this:
Usage: gherkin-lint [options]
This made me think that the linter somehow searches for
the *.feature files by itself.  Took me a while to figure out
that they actually need to be specified from command line.
After this change, the usage info is:
Usage: gherkin-lint [options] <feature-files>

Document that feature files need to be specified

---

README.md

Also tried to improve the rules list in README overall:
- Sorted the rules alphabetically.
- Removed "Configurable" column, leaving just `*` marks for non-configurable rules.
- Separated the two groups of rules by empty row.
- Linked the rules with config options to the specific section in README.
Would be nice to have a separate pages for each rule where each would be fully documented with some example code, like done in ESLint docs.
PS. Could you also do a release. I'd really like to put this `no-restricted-tags` into use.

Document no-restricted-tags

---

README.md
package.json
src/config-parser.js
src/linter.js
src/main.js
src/rules.js
test/rulesdir/.gherkin-lintrc
test/rulesdir/other_rules/custom.js
test/rulesdir/rules/custom.js
test/rulesdir/rulesdir.js
test/rulesdir/simple.features

This allows passing custom rules directories, similar to the [eslint --rulesdir option](http://eslint.org/docs/user-guide/command-line-interface#--rulesdir) that will be searched for rules.
Fixes #70

Allow custom rules directories

---

README.md
src/rules/no-duplicate-tags.js
test-data-wip/.gherkin-lintrc
test-data-wip/DuplicateTags.feature
test/rules/no-duplicate-tags/test-data/NoViolations.feature
test/rules/no-duplicate-tags/test-data/Violations.feature
test/rules/no-duplicate-tags/test-results/results.js
test/rules/no-duplicate-tags/test.js

I needed this custom rule, but it seemed generic enough that you might want it.  It prevents duplicate tags on a feature or scenario.
I have a couple more slightly less generic rules which I can raise PRs for as well, if you'd like them?  They are:
1. Failing if the same tag is specified on a feature and on one of it's scenarios (no-unnecessary-tags?)
2. Failing if the same tag is specified on every scenario in a feature (it should be feature level instead).
Simon

Add no-duplicate-tags rule

---

src/feature-finder.js
test/configuration-parser/test.js
test/feature-finder/test.js

Currently, it is possible to get errors (for example for unique scenario names) by passing something like: `gherkin-lint src src/x.feature` - `x.feature` would be picked up twice and then error.
This PR fixes this.
cc @brendanAnnable

fix: do not pick up duplicates

---

src/rules/indentation.js

Since `parsedLocation` is passed by reference, when doing the
subtraction, it is important to not modify the value.
- Fixes #99

Do not modify value of parsedLocation.column when doing comparison.

---

src/config-verifier.js
test/rulesdir/.gherkin-lintrc
test/rulesdir/other_rules/custom-list.js
test/rulesdir/rulesdir.js

I have been creating a new rule to check if a step have some key words and I have some problem launching this rule.
It seems that in the gherkin-lint/src/config-verifier.js file, when calling the getRule method, the additionalRulesDirs (which contains the path to my own rules) is not specified.
To fix it, it's needed to add the additionalRulesDirs parameter in all the getRule method calls, which implies add the parameter to verifyRuleConfiguration and testSubconfig method.
Included fix and test to check that the avalaible config is allowed in the custom rules

Issue #109

---

.travis.yml
package-lock.json
package.json
test/rules/no-unused-variables/no-unused-variables.js

- Closes #144 #145 
- Bumps patch version to `3.0.1`
- Updates Travis CI script to use Node 10, Node 8, and Node 6. Node 11 does not work with gherkin lint in gherkin-lint's master branch. I didn't sweat it as [Node 11 is not LTS](https://github.com/nodejs/Release#nodejs-release-working-group) and is in current development and not guaranteed to be stable. I thought you'd want to serve all past and current Long Term Support (LTS) Node versions.
@vsiakka - Please review
Fixes 173 moderate vulnerabilities in 2697 packages with updates to lodash and eslint.

Fix: Removes moderate vulnerabilities

---

.travis.yml
package-lock.json
src/rules/indentation.js
src/rules/one-space-between-tags.js

The rules broke because the behavior os Array.sort() changed in node 11
as described in https://github.com/nodejs/node/issues/24294

Fix the indentation and one-space-between-tags rules in node 11

---

src/rules/indentation.js
src/rules/no-scenario-outlines-without-examples.js
test/rules/no-scenario-outlines-without-examples/NoViolations.feature
test/rules/no-scenario-outlines-without-examples/ViolationsEmptyExamples.feature
test/rules/no-scenario-outlines-without-examples/ViolationsNoExamples.feature
test/rules/no-scenario-outlines-without-examples/ViolationsNoExamplesBody.feature
test/rules/no-scenario-outlines-without-examples/no-scenario-outlines-without-examples.js

- Resolves #154
- Adds unit tests to `no-scenario-outlines-without-examples` rule
- Fixes crash in the indentation rule when an empty examples table is used

Fix bugs related to empty examples tables

---

package.json
src/rules/no-homogenous-tags.js
src/rules/no-partially-commented-tag-lines.js
test-data-wip/.gherkin-lintrc
test-data-wip/NoHomogenousTags.feature
test/rules/no-homogenous-tags/NoViolations.feature
test/rules/no-homogenous-tags/Violations.feature
test/rules/no-homogenous-tags/no-homogenous-tags.js

Additionally:
- Remove console.log statement from allowed tags rule, which was a
leftover from debugging
- Make demo only run against features in test-data-wip folder and check
for dupe scenario names just inside the same feature, so that its output
is shorter
fixes: #166

Fix no-homogenous-tags rule not working with examples

---

package.json

To avoid https://snyk.io/vuln/SNYK-JS-LODASH-450202

security: ugrade lodash to v4.17.14

---

README.md
src/formatters/stylish.js

- vertically align errors on a per file basis instead of doing it for all the files
- when the linter detects that it's running in tty, don't take into account error messages that are longer than the console width, when calculating alignment rules
These changes should make the error output more readable and pretty when the linter reports errors with really long messages (eg duplicate scenario names)

 stylish improvements 

---

README.md

Fix small typo for no-restricted-patterns rule configuration where `{}` was used. It should be `[]` since the values are arrays.

Fix example typos for no-restricted-patterns

---

README.md
package-lock.json
package.json
src/config-parser.js
test/config-parser/config-parser.js
test/config-parser/good_config_with_comments.gherkinrc

It's useful to be able to provide a comment-annotated lint config file as living policy documentation.
This adds support for JavaScript-style comments being present in the config file, and just strips them off right before parsing into an object, using https://github.com/sindresorhus/strip-json-comments (as used by ESLint for same purpose).

add support for comments in config file

---

README.md
src/rules/max-scenarios-per-file.js
test/rules/max-scenarios-per-file/max-scenarios-per-file.js

Adds another configuration option to the `max-scenarios-per-file` rule so that you can specify whether each row in a Scenario Outline table should be counted towards the number of scenarios (the current, and still default, behaviour) or whether the whole outline block should just count as 1.

configure max-scenarios-per-file for whether each row of a Scenario Outline is counted

---

README.md

Value for `max-scenarios-per-file` should be a list.

Fix documentation for `max-scenarios-per-file` and `no-restricted-patterns`

---

package.json

To avoid https://snyk.io/test/npm/lodash/4.17.19

security: ugrade lodash to v4.17.20

---

package-lock.json
package.json

This PR upgrades `lodash` to `4.17.21` to include a security fix. It also runs `npm dedupe` to consolidate the lock file.

Upgrade lodash for security fix

---

src/rules/no-unused-variables.js
test/rules/no-unused-variables/NoViolations.feature

Ignore `no-unused-variables` when there's no Examples table

---

README.md
src/rules/allowed-tags.js
src/rules/no-restricted-tags.js
test/rules/allowed-tags/NoViolations.feature
test/rules/allowed-tags/allowed-tags.js
test/rules/no-restricted-tags/no-restricted-tags.js

Resolves #227
This adds a `"patterns"` configuration property to the `allowed-tags` and `no-restricted-tags` rules, which can be combined with the existing `"tags"` property to allow or forbid a list of patterns. This also changes the description of the `allowed-tags` in the README, since it was erroneous.

Add pattern support to tag rules

---

README.md
src/rules/required-tags.js
test/rules/required-tags/Violations.feature
test/rules/required-tags/required-tags.js

Resolves #238 
This adds an `"ignoreUntagged"` configuration property to the `required-tags` rule. The default value is `true` to retain the current behaviour. When the option is set to `false`, scenarios that do not have any tag are no longer ignored by the rule (and an error will be reported if the list of required tag patterns is not empty).

Add required-tags option to check untagged scenarios

---

package-lock.json
package.json
src/formatters/xunit.js
src/main.js

Add support for j/xunit formatting, see #240 
Example output for failing tests: 
Json input: 
```json
{
"filePath":"C:\\[redacted]\\UseAnd.feature",
"errors":[ 
{"message":"Backgrounds are not allowed when there is just one scenario.","rule":"no-background-only-scenario","line":3},
{"message":"Step \"Given third statement that does not use and\" should use And instead of Given ","rule":"use-and","line":6}, 
{"message":"Step \"When second step without and\" should use And instead of When ","rule":"use-and","line":11}, 
{"message":"Step \"Then second assertion without and\" should use And instead of Then ","rule":"use-and","line":14}
]
}
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuite name="gherkin-lint">
<testcase name="C:\[redacted]\gherkin-lint\test-data-wip\UseAnd.feature"> …
```

Add xunit formatter

---

.github/workflows/npm_publish.yml
.github/workflows/npm_test.yml
.travis.yml
README.md
package.json

This commit:
- removes the travis configuration
- adds a GHA for testing
- fixes the existing npm_publish to use the current LTS version of Node rather than the development version from v16
For the new GHA I have set the build versions to every release version of Node from 10 to 20.
I have also updated the publish action to use Node 18 (current LTS) instead of 15 (development version).

Migrate from Travis to GitHub Actions
