gherkin-lint/gherkin-lint

- src/rules/indentation.js
The indentation doesn't need to be spaces, can be tabs, too. Because of that wording is changed to "indentation level"
> Update indentation error message

- .editorconfig
My editor was messing up the files, since our company policy are tabs ;)
Hope this helps to enforce a consistent coding style.
> chore: added editorconfig to the project

- README.md
- src/rules/indentation.js
- test-data/WrongIndentionDifferentLanguage.feature
This allows a flexible configuration of each step indentation level :)
(we indent And and But one level deeper)
> feat: make each step configurable in indentation rule

- src/rules.js
- src/rules/indentation.js
> Indentation fallback

- package.json
- src/linter.js
- src/rules/indentation.js
- src/rules/no-dupe-scenario-names.js
- src/rules/no-files-without-scenarios.js
- src/rules/no-partially-commented-tag-lines.js
- src/rules/no-unamed-features.js
- src/rules/no-unamed-scenarios.js
- test-data/DuplicateScenarioName.feature
BREAKING CHANGES: this version requires Gherkin >=4.0.0 and is not compatible with prior releases of Gherkin
This fixes #32 
Please do some tests, too - I might have missed something 👍
> feat: add Gerkin 4 support

- README.md
I hope you agree that badges are
1. awesome
2. helpful
Cheers
> docs: add badges to the README

- src/config-parser.js
- test/configuration-parser/test.js
Hi,
This is the PR to solve the side effect in `getConfiguration` method metioned in #54 
Thanks!
> fix configParser.getConfiguration side effect

- README.md
- src/rules/no-unnamed-features.js
- src/rules/no-unnamed-scenarios.js
- test-data-wip/.gherkin-lintrc
- test-data-wip/UnnamedFeature.feature
- test-data-wip/UnnamedScenario.feature
- test/configuration-parser/test-data/config1
- test/configuration-parser/test-results/results.js
Fixes: https://github.com/vsiakka/gherkin-lint/issues/58
> Fixing spelling on no-unnamed-scenario and no-unnamed-feature rules

- src/linter.js
- src/rules.js
- src/rules/indentation.js
- src/rules/name-length.js
- src/rules/new-line-at-eof.js
- src/rules/no-dupe-feature-names.js
- src/rules/no-dupe-scenario-names.js
- src/rules/no-empty-file.js
- src/rules/no-files-without-scenarios.js
- src/rules/no-multiple-empty-lines.js
- src/rules/no-partially-commented-tag-lines.js
- src/rules/no-scenario-outlines-without-examples.js
- src/rules/no-trailing-spaces.js
- src/rules/no-unnamed-features.js
- src/rules/no-unnamed-scenarios.js
Surfing around in the code I discovered that several rules read in the feature file again, this seemed unnecessary work as the file is already read in before parsing it with Gherkin.
So decided to tackle this shortcoming and along the way discovered some other bugs that I fixed as well.
See commit comments.
> Read feature files once

- src/config-parser.js
Fixes this defect: 
https://github.com/vsiakka/gherkin-lint/issues/73
> Fixed on/off rule check

- README.md
- package.json
- src/rules/no-homogenous-tags.js
- src/rules/no-superfluous-tags.js
- test-data-wip/.gherkin-lintrc
- test-data-wip/NoHomogenousTags.feature
- test-data-wip/NoSuperfluousTags.feature
- test/rules/no-homogenous-tags/test-data/NoViolations.feature
- test/rules/no-homogenous-tags/test-data/Violations.feature
- test/rules/no-homogenous-tags/test-results/results.js
- test/rules/no-homogenous-tags/test.js
- test/rules/no-superfluous-tags/test-data/NoViolations.feature
- test/rules/no-superfluous-tags/test-data/Violations.feature
- test/rules/no-superfluous-tags/test-results/results.js
- test/rules/no-superfluous-tags/test.js
As promised, two new rules for tags.
I'm not sure about the no-homogenous-tags name - but I can't think of anything better - unless you've got a good idea?
> Add no-superfluous-tags and no-homogenous-tags rules

- README.md
- src/rules/one-space-between-tags.js
- test-data-wip/.gherkin-lintrc
- test/rules/one-space-between-tags/NoViolations.feature
- test/rules/one-space-between-tags/Violations.feature
- test/rules/one-space-between-tags/one-space-between-tags.js
One last rule that I thought others might need.
> Add one-space-between-tags rule

- README.md
- src/rules/allowed-tags.js
- src/rules/no-background-only-scenario.js
- src/rules/no-empty-background.js
- test-data-wip/.gherkin-lintrc
- test/rules/allowed-tags/NoViolations.feature
- test/rules/allowed-tags/Violations.feature
- test/rules/allowed-tags/allowed-tags.js
- test/rules/no-background-only-scenario/NoBackground.feature
- test/rules/no-background-only-scenario/NoViolations.feature
- test/rules/no-background-only-scenario/ViolationsOutline.feature
- test/rules/no-background-only-scenario/ViolationsScenario.feature
- test/rules/no-background-only-scenario/no-background-only-scenario.js
- test/rules/no-empty-background/NoBackground.feature
- test/rules/no-empty-background/NoViolations.feature
- test/rules/no-empty-background/Violations.feature
- test/rules/no-empty-background/no-empty-background.js
Created the rules for issues:
- #97 
- #100 
- #101 
There is a small change in _no-restricted-tags_ rule.
There was an issues with the error message, it showed the scenario/background line instead of the tag line.
@znevrly and @ajthesnare ; please, check if it's waht you expected
> New rule for issues #97, #100 and #101

- src/rules/max-scenarios-per-file.js
- test/rules/max-scenarios-per-file/CorrectNumber.feature
- test/rules/max-scenarios-per-file/CorrectNumberExamples.feature
- test/rules/max-scenarios-per-file/CorrectNumberMixed.feature
- test/rules/max-scenarios-per-file/TooManyExamples.feature
- test/rules/max-scenarios-per-file/TooManyScenarios.feature
- test/rules/max-scenarios-per-file/max-scenarios-per-file.js
Add rule to specify maximum number of scenarios per file. defaulted to 10.
> Add maximum scenarios per file rule

- src/rules/max-scenarios-per-file.js
- test/rules/max-scenarios-per-file/max-scenarios-per-file.js
> Fix the default configuration for the maxScenarios rule

- package-lock.json
- src/rules/no-unused-variables.js
- test/rules/no-unused-variables/NoViolations.feature
- test/rules/no-unused-variables/UnusedExampleVariables.feature
- test/rules/no-unused-variables/UnusedStepVariables.feature
- test/rules/no-unused-variables/no-unused-variables.js
- variables were not correctly detected in scenario names
- variables were not correctly detected in step arguments (DocString or DataTable)
- words between < and > in Backgrounds and Scenarios would incorrectly be counted as variables even though they are treated like strings
> Fix bugs with the no-unused-variables rule:

- .travis.yml
- package-lock.json
- package.json
- src/feature-finder.js
- src/linter.js
- src/rules/allowed-tags.js
- src/rules/indentation.js
- src/rules/name-length.js
- src/rules/new-line-at-eof.js
- src/rules/no-background-only-scenario.js
- src/rules/no-dupe-feature-names.js
- src/rules/no-dupe-scenario-names.js
- src/rules/no-duplicate-tags.js
- src/rules/no-empty-background.js
- src/rules/no-empty-file.js
- src/rules/no-files-without-scenarios.js
- src/rules/no-homogenous-tags.js
- src/rules/no-multiple-empty-lines.js
- src/rules/no-partially-commented-tag-lines.js
- src/rules/no-restricted-tags.js
- src/rules/no-scenario-outlines-without-examples.js
- src/rules/no-superfluous-tags.js
- src/rules/no-trailing-spaces.js
- src/rules/no-unnamed-features.js
- src/rules/no-unnamed-scenarios.js
- src/rules/use-and.js
- test/feature-finder/feature-finder.js
- test/linter/linter.js
[Previous PR](https://github.com/vsiakka/gherkin-lint/pull/119)
Best regards.
> Updated all npm dependencies

- .babelrc
- .travis.yml
- README.md
- package-lock.json
- package.json
This PR is porting @JuanMaRuiz 's change from https://github.com/vsiakka/gherkin-lint/pull/131 since I didn't merge that PR on time and it end up having conflicts.
> Add a coveralls to report code coverage with a badge and with comments in PRs

- src/rules/allowed-tags.js
- test/rules/allowed-tags/Violations.feature
- test/rules/allowed-tags/allowed-tags.js
> Fix allowed-tags rule not working on Examples nodes

- src/rules/no-duplicate-tags.js
- test/rules/no-duplicate-tags/Violations.feature
- test/rules/no-duplicate-tags/no-duplicate-tags.js
> fix no-duplicate-tags rule not working in Examples nodes

- src/rules/one-space-between-tags.js
- test/rules/one-space-between-tags/NoViolations.feature
- test/rules/one-space-between-tags/Violations.feature
- test/rules/one-space-between-tags/one-space-between-tags.js
> Fix one-space-between-tags rule not detecting errors in Examples nodes

- src/rules/no-unnamed-scenarios.js
- test/rules/no-unnamed-scenarios/Violations.feature
- test/rules/no-unnamed-scenarios/no-unnamed-scenarios.js
> Fix no-unnamed-scenarios rule not working for scenario outlines

- src/feature-finder.js
- test/feature-finder/feature-finder.js
Fixes https://github.com/vsiakka/gherkin-lint/issues/216
> Ignore directories with *.feature name

- src/config-parser.js
- src/config-verifier.js
- src/feature-finder.js
- src/formatters/stylish.js
- src/linter.js
- src/main.js
- src/rules.js
- src/rules/allowed-tags.js
- src/rules/indentation.js
- src/rules/max-scenarios-per-file.js
- src/rules/name-length.js
- src/rules/no-background-only-scenario.js
- src/rules/no-dupe-scenario-names.js
- src/rules/no-duplicate-tags.js
- src/rules/no-empty-background.js
- src/rules/no-homogenous-tags.js
- src/rules/no-partially-commented-tag-lines.js
- src/rules/no-restricted-patterns.js
- src/rules/no-restricted-tags.js
- src/rules/no-scenario-outlines-without-examples.js
- src/rules/no-superfluous-tags.js
- src/rules/no-trailing-spaces.js
- src/rules/no-unnamed-scenarios.js
- src/rules/no-unused-variables.js
- src/rules/one-space-between-tags.js
- src/rules/required-tags.js
- src/rules/use-and.js
- src/rules/utils/gherkin.js
Applied the following transforms using [lebab](https://github.com/lebab/lebab):
- arrow
- arrow-return
- let
- includes
final fix for #62
> Transforms to es6

- src/rules/indentation.js
- src/rules/name-length.js
- src/rules/no-superfluous-tags.js
- src/rules/scenario-size.js
- src/rules/use-and.js
- src/rules/utils/gherkin.js
This is to resolve the errors from #233 
In file `src/rules/use-and.js`, added `if (node.steps)` to prevent null error.
> Add support for rule keyword

- CHANGELOG.md
- package.json
- src/rules/keywords-in-logical-order.js
- src/rules/no-files-without-scenarios.js
- test-data-wip/KeywordsInLogicalOrder.feature
- test/rules/keywords-in-logical-order/NoViolationsUsingRules.feature
- test/rules/keywords-in-logical-order/ViolationsUsingRules.feature
- test/rules/keywords-in-logical-order/keywords-in-logical-order.js
- test/rules/no-files-without-scenarios/FeatureWithRuleAndScenario.feature
- test/rules/no-files-without-scenarios/FeatureWithRuleAndScenarioOutline.feature
- test/rules/no-files-without-scenarios/ViolationsWithRule.feature
- test/rules/no-files-without-scenarios/no-files-without-scenarios.js
This is a replacemnt for #253 and solves #254, #255 and possibly others.
Unfortunately I can't push to 253 so I'll close that issue in favour of this one where I've removed a meaningless commit and rebased.
> Support rules

- CHANGELOG.md
- README.md
- src/rules/only-one-when.js
- test/rules/only-one-when/NoViolations.feature
- test/rules/only-one-when/NoViolationsUsingRules.feature
- test/rules/only-one-when/Violations.feature
- test/rules/only-one-when/ViolationsUsingRules.feature
- test/rules/only-one-when/only-one-when.js
* Add tests and supporting feature files
* Add only-one-when.js to implement feature
* Add entry to README
> Add support for only-one-when step check, issue #255
